### ISSUE TITLE
kubeseal failing to execute in Cloud9 environment 

### ISSUE THREAD

**Issue by rizblie** [aws-samples/eks-multi-cluster-gitops#65]
kubeseal failing with `cannot execute binary file: Exec format error`

This is due to use of the darwin (Mac OSX) release when installing. Need to change to Linux release.

**Comment by iamahgoub** [comment]
Cleaning-up issues; this is addressed as part of PR: https://github.com/aws-samples/eks-multi-cluster-gitops/pull/66.
