### ISSUE TITLE
Cloud9 failing to reconnect to instance

### ISSUE THREAD

**Issue by rizblie** [aws-samples/eks-multi-cluster-gitops#67]
After a Cloud9 timeout it is no longer possible to  reconnect to the Cloud9 instance.

Appears to be related to a move to SSM for connecting to instances, which requires the correct IAM permissions (specifically the managed policy `AmazonSSMManagedInstanceCore`) to be included in the EC2 instance IAM role.

Note: Cloud9 now attaches a role with this policy this by default, but we are replacing this default role with the `gitops-workshop` role plus a restricted set of permissions.

**Comment by iamahgoub** [comment]
Cleaning-up issues; this is addressed as part of PR: https://github.com/aws-samples/eks-multi-cluster-gitops/pull/68.
