### ISSUE TITLE
Trim mgmt cluster manifests

### ISSUE THREAD

**Issue by rizblie** [aws-samples/eks-multi-cluster-gitops#70]
Flux on the management cluster does not need `sealed-secrets` to access `gitops-system`, as the credentials are passed as part of flux bootstrap.

This means that the manifests for the mgmt cluster can be trimmed to include just the crossplane-related and clusters-config kustomizations.

**Comment by iamahgoub** [comment]
Cleaning-up pending issues; this is addressed in PR: https://github.com/aws-samples/eks-multi-cluster-gitops/pull/73.
