### ISSUE TITLE
Fix health check for workload cluster sealed-secrets

### ISSUE THREAD

**Issue by rizblie** [aws-samples/eks-multi-cluster-gitops#71]
The current manifest for workload cluster sealed-secrets incorrectly performs a health check on a local (management cluster) deployment instead of the workload cluster. This does not perform any useful function and should be removed. The existing HelmRelease healthcheck (which deploys to the remote workload cluster) should suffice.

**Comment by iamahgoub** [comment]
Cleaning-up pending issues; this is addressed in PR: https://github.com/aws-samples/eks-multi-cluster-gitops/pull/73.
