### ISSUE TITLE
Inital setup - Missing clone for CodeCommit repos

### ISSUE THREAD

**Issue by rizblie** [aws-samples/eks-multi-cluster-gitops#72]
In the intial setup instructions, the CodeCommit repo creation process does not clone the repos locally.
Subsequently, the instructions to populate the repos fail.

**Comment by iamahgoub** [comment]
Cleaning-up issues; this is addressed as part of PR: https://github.com/aws-samples/eks-multi-cluster-gitops/pull/73.
