### ISSUE TITLE
No REPO_PREFIX placeholder exists

### ISSUE THREAD

**Issue by shankey28** [aws-samples/eks-multi-cluster-gitops#89]
Under Initial set up:

Update references to GitRepository URLs

Step 4: 
sed -i "s~REPO_PREFIX~$REPO_PREFIX~g" \
  gitops-workloads/template/app-template/git-repo.yaml

No REPO_PREFIX variable exists in git-repo.yaml file

**Comment by iamahgoub** [comment]
Can you please clarify? I see the placeholder in the file: https://github.com/aws-samples/eks-multi-cluster-gitops/blob/8c766a635b6527d2b0b9c158403b1e717259b1e6/repos/gitops-workloads/template/app-template/git-repo.yaml#L13

You may have checked the file after you have already executed the sed command.
